apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::700651439719:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1JDMEU2OII97U
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-11T20:24:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1476"
  uid: 51c5509d-754e-44df-8a84-566a522eda10
